export const CONSTANTS = {
  NAME: "Name",
  EMAIL: "Email",
  ADDRESS: "Address",
  SIGN_UP: "Sign up",
  PASSWORD: "Password",
  FORGOT_PASSWORD: "Forgot Password",
  CONFIRM_PASSWORD: "Confirm Password",
  RESET_PASSWORD: "Reset Password",
  ALREADY_ACCOUNT: "Already have an account",
  DONT_ACCOUNT: "Don't have an account",
  LOGIN: "Login",
  EMAIL_ADDRESS: "Email Address",
  FEMALE: "Female",
  MALE: "Male",
  CITY: "City",
  STATE: "State",
  FIRST_NAME: "First Name",
  LAST_NAME: "Last Name",
  SOMETHING_WRONG: "Something went wrong",
  MOBILE_NUMBER: "Mobile Number",
  ADD_NEW_ADDRESS: "+ ADD A NEW ADDRESS",
  ALREADY_LOGOUT: "You are already Logout!",
  LOGOUT: "Log Out",
  SEARCH: " Search",
  HOME: "Home",
  SHOP: "Shop",
  ACCOUNT: "Account",
  MY_PROFILE: "My Profile",
  MY_WISHLIST: "My Wishlist",
  SAVE_LIST: "Save List",
  DELIVERY_HERE: "DELIVERY HERE",
  DEFAULT_MOBILE_NUMBER: "6352075082",
  RESET_LINK_MSG: "Check your email for the password reset link.",
  CURRENT_USER_NOT_FOUND: "No current user found! Please login.",
  EXTRA_CASHON_DELIVERY_CHARGE:
    "Due to handling costa, a nominal fee of ₹7 will be charged",
  REGISTRED_EMAIL:
    "This email is already registered. Please use a different email.",
};
