export const ROUTES = {
  DEFAULT_PATH: "/",
  LOGIN: "/login",
  SIGN_UP: "/signup",
  SHOP: "/shop",
  PRODUCT_PRODUCTID: "/products/:productID",
  PRODUCT_CATEGARTNAME: "/products/category/:categoryName",
  CART: "/cart",
  PAYMENT: "/payment",
  CONFIR_MATION: "/confirmation",
  CHECKOUT: "/checkout",
  WISHLIST: "/wishlist",
  SAVEFOR_LATER: "/saveforlater",
  FORGOT_PAAWORD: "/forgot-password",
  RESET_PASSWWORD: "/reset-password",
  REVIEW: "/review",
  PROFILE: "/profile",
  PAGE_404: "/*",
};
